#+TITLE: Notas de Estudos: Analise de Componentes Principais (PCA)
#+AUTHOR: Eu e o Gemini

* Introducao

Este documento sao notas de estudos sobre analise de componentes
principais

Criei um csv a partir dos dados de exemplo que o professor utilizou em
seus slides pra manter a linha do que o prof explicou

Pra realmente entender trouxe as operacoes matematicas pertinentes ao
calculo dos componentes principais.


* Dados de Estudo

Pra rodar as analises é só clonar esse repositorio e rodar com o
comando abaixo. Claro, adaptando os diretorios conforme o seu computador e
sistema operacional e nao esquecendo de ativar o venv.


#+name: (venv) wgn@fedora:~/WORKING/Projects-Srcs/Projects-Srcs-FzlSoft/curso_estatistica_multivariada/exercicios$ python3 exercicio_0_pca_dados_slide/src/main.py 
#+begin_src shell
(venv) wgn@fedora:~/WORKING/Projects-Srcs/Projects-Srcs-FzlSoft/curso_estatistica_multivariada/exercicios$ python3 exercicio_0_pca_dados_slide/src/main.py 
#+end_src

O trecho que carrega e mostra os dados que vamos utilizar para as
notas de estudo estão abaixo.


#+BEGIN_SRC python
import pandas as pd
from data_io.data_loader import load_pca_data
pd.set_option('display.max_columns', 10)
csv_path = 'exemplo_pca.csv'
data = load_pca_data(csv_path)
print(data.head())
#+END_SRC


| unidade |  X1 |  X2 |  X3 |
|---------+-----+-----+-----|
|     1.0 | 2.0 | 4.0 | 5.0 |
|     2.0 | 3.0 | 5.0 | 3.0 |
|     3.0 | 6.0 | 4.0 | 3.0 |
|     4.0 | 4.0 | 2.0 | 1.0 |
|     5.0 | 3.0 | 1.0 | 1.0 |
|     6.0 | 6.0 | 1.0 | 4.0 |


* Notacoes Matriciais

Acima temos os dados trazidos pela leitura do python, na notação
matricial temos:


\begin{equation}
X = \begin{bmatrix} 
2.0 & 4.0 & 5.0 \\
3.0 & 5.0 & 3.0 \\
6.0 & 4.0 & 3.0 \\
4.0 & 2.0 & 1.0 \\
3.0 & 1.0 & 1.0 \\
6.0 & 1.0 & 4.0
\end{bmatrix}
\end{equation}


* Vetor de Medias

** Operacao Matricial
\begin{equation}
\bar{x} = \frac{1}{n} X^T \mathbf{1}
\end{equation}

** Passo a Passo
- Transposta:
\begin{equation}
X^T = \begin{bmatrix} 2 & 3 & 6 & 4 & 3 & 6 \\ 4 & 5 & 4 & 2 & 1 & 1 \\ 5 & 3 & 3 & 1 & 1 & 4 \end{bmatrix}
\end{equation}

- Soma das colunas (X^T * 1):
\begin{equation}
\begin{bmatrix} 24 \\ 17 \\ 17 \end{bmatrix}
\end{equation}

- Media Final:
\begin{equation}
\bar{x} = \begin{bmatrix} 4.0 \\ 2.833 \\ 2.833 \end{bmatrix}
\end{equation}

* Padronizacao (Standardization)
Para evitar que variaveis com escalas muito diferentes distorcam a analise, aplicamos a padronizacao (Z-score).

** Formula Matricial Global
A operacao para padronizar toda a matriz \(X\) simultaneamente e:

\begin{equation}
Z = (X - \mathbf{1}\bar{x}^T) D^{-1}
\end{equation}

Onde:
- \(X\) e a matriz original.
- \(\mathbf{1}\) e um vetor de uns.
- \(\bar{x}^T\) e o vetor de medias transposto.
- \(D^{-1}\) e a inversa da matriz diagonal de desvios padrao.

* Covariancia
\begin{equation}
R = \frac{1}{n-1} Z^T Z
\end{equation}

* Equacao Caracteristica
\begin{equation}
det(R - \lambda I) = 0
\end{equation}
