#+Title: Análise de Agrupamento

Segue anotações de estudos da leitura do livro do hair

Conjunto de técnicas multivariadas de interdependência

Objetiva encontrar grupos de objetos ou indivíduos o mais similares
possível dentro do grupo e mais diferentes possível entre os grupos.

Com isso os objetos classificados podem ser vistos como membros de um
perfil geral (grupo) em vez de entidades únicas

O pesquisador utiliza a técnica para descobrir os grupos, ou seja, ele
ainda não sabe quais grupos existem. Na técnica de análise
discriminante o pesquisador já conhece os grupos antes de rodar a análise.

A análise é um processo estruturado em 6 estágios

1. Delinear Objetivos da Análise

   - taxomonia e simplificação:
     Escolha das variáveis de classificação
     
     Fazer a escolha fundamentada na literatura ou bem justificada
     
     Pode ser feita uma Análise de Componentes principais para
     identificar variáveis estatísticamente relevantes e/ou
     irrelevantes
     
   - Avaliar bem o comportamento das variávei escolhidas
     Máximo cuidado com outlieres
     
     Fundamental padronizar na distribuição z pois o que interessa não
     é a medida em sí mas principalmente as diferenças dessa medida
     (variável) entre os objetos
     
     Não se exige distribuição normal para as variáveis selecionadas
     para o agrupamento
     
     Padronizar a variável não significa que depois de padronizada ela     
     vai seguir a distribuição normal
     
     Multicolinearidade entre as variáveis distorcem o resultado.
     
   - fazer análises posteriores investigando as diferenças e
     semelhanças de acordo com a literatura
     
   - Decidir qual medidas de similiraidade e qual algoritmo
     Percebi que é importante tomar essas duas decisoes em conjunto
     Medidas populares: Euclidiana ou a de Mahalanobis
     
     Os algoritmos podem ser hierarquicos (wald) ou vc escolhe o
     número de grupos antes de rodar a técnica (kmeans puro). Existe
     um algoritmo que não é hierárquico que é Elbow (cotovelo) que
     roda varios agrupamentos e escolhe o melhor. Também tem o
     coeficiente da silhueta.
     
     Tem como fazer uma técnica híbrida para conseguir um dendograma
     quando tiver rodando um algoritmo não hierárquico.

2.  Representatividade da amostra:
    Necessário para inferências estatística. 

3. Não existe o melhor agrupamento, isso vai depender da expertise do pesqusisador

4. Hair frequentemente recomenda uma abordagem combinada: usar um método
hierárquico primeiro para determinar o número ideal de grupos e gerar
pontos semente,

aplicando em seguida um método não-hierárquico para alocar e refinar os resultados

6. Considerando que a técnica é exploratório o melhor agrupamento pode
   depender do pesquisdor, validar os grupos é obrigatório.
   A validadação pode ser comprovando com análise de variáncia que os
   grupos realmente diferem entre sí ou técnicas similares.
   
